### ISSUE TITLE
repbase

### ISSUE THREAD

**Issue by toto2011** [clemgoub/dnaPipeTE#20]
it seems giri asks for non-free subscription to obtain the RM libraries so my username and password are only getting some xml file from their repository. any ideas how to solve this? would a flat fasta be enough?

thanks!

**Comment by clemgoub** [comment]
Hello toto2011,

Indeed RepBase has moved to a subscription-based mode and this impacts the installation of dnaPipeTE. 

One quick fix is to obtain the fasta sequence of the RepeatMasker libraries and pass it in the command line with the `-RM_lib` argument.

 The format must be as follow:

`>TE_NAME#Class/Subclass` with Class/Subclass identical to the list available in the first column of the file `new_list_of_RM_superclass_colors_sortedOK`
Otherwise TE will be classified as "unknown".

I'm looking for a more user friendly solution, but seems that the new rules on Repbase will make it difficult.

Please let me know if you have any trouble,

Clément

**Comment by clemgoub** [comment]
Closing this issue since it concerns the non-container version. Please DM if further support is needed. Thank you!
