### ISSUE TITLE
Reading Trinity output files

### ISSUE THREAD

**Issue by Tidler123** [clemgoub/dnaPipeTE#21]
Hi,
I'm having some trouble understanding the length of repeats given in the Trinity.fasta.out files.
Under repeat 'begin' and 'end' (which I'm assuming will give the length if deducted from one another) some values appear in brackets () and sometimes does not make sense (i.e. begin larger than end).
Could you please clarify?
Cheers

**Comment by clemgoub** [comment]
Hello!

The `Trinity.fasta.out` file is the Repeat Masker output for your dnaPipeTE contigs present in the file `Trinity.fasta` (query). The Repeat Masker output is indeed a little odd; here is the example from the RepeatMasker website:

``` 
  SW  perc perc perc  query    position in query     matching repeat      position in  repeat
score div. del. ins.  sequence begin  end  (left)    repeat  class/family   begin end (left) ID
...
 1320 15.6  6.2  0.0  HSU08988  6563 6781 (22462) C  MER7A   DNA/MER2_type    (0)  337  104  20
```

'begin' and 'end' represent the start and stop of the hit for the contig ("position in query", here fro, 6563 to 6781) and then later on for the reference TE in the database ("position in repeat", from 104 to 307). Because the TE can be in the + or - orientation regarding the database, if your query is in the reverse orientation regarding the database, the "position in repeat" will be flipped (here : 337 to 104). You can also notice the "C" in the unamed column (between "(left)" and "repeat"). Finally, the brackets are the remaining number of bp either:
- in the query, after the hit (here there is 22462bp left in the query)
- in the database, also after the hit (here 0, meaning the hit starts at the 104th base and extend to the end of the database sequence).

Thus, to get the length of your assembled contig you can sum the "query end" and "query left", in the example this will be: 6781 (end of the hit) + 22462 (bp left after the hit). 

Finally here is a copy and paste of the Repeat Masker help page about it:

```
  SW  perc perc perc  query    position in query     matching repeat      position in  repeat
score div. del. ins.  sequence begin  end  (left)    repeat  class/family   begin end (left) ID
...
 1320 15.6  6.2  0.0  HSU08988  6563 6781 (22462) C  MER7A   DNA/MER2_type    (0)  337  104  20
12279 10.5  2.1  1.7  HSU08988  6782 7718 (21525) C  Tigger1 DNA/MER2_type    (0) 2418 1486  19
 1769 12.9  6.6  1.9  HSU08988  7719 8022 (21221) C  AluSx   SINE/Alu         (0)  317    1  17
12279 10.5  2.1  1.7  HSU08988  8023 8694 (20549) C  Tigger1 DNA/MER2_type  (932) 1486  818  19
 2335 11.1  0.3  0.7  HSU08988  8695 9000 (20243) C  AluSg   SINE/Alu         (5)  305    1  18
12279 10.5  2.1  1.7  HSU08988  9001 9695 (19548) C  Tigger1 DNA/MER2_type (1600)  818    2  19
  721 21.2  1.4  0.0  HSU08988  9696 9816 (19427) C  MER7A   DNA/MER2_type  (224)  122    2  20

This is a sequence in which a Tigger1 DNA transposon has integrated into a MER7 DNA transposon copy. Subsequently two Alus integrated in the Tigger1 sequence. The first line is interpreted as such:

  1320     = Smith-Waterman score of the match, usually complexity adjusted
        The SW scores are not always directly comparable. Sometimes
        the complexity adjustment has been turned off, and a variety of
        scoring-matrices are used dependent on repeat age and GC level.

  15.6     = % divergence = mismatches/(matches+mismatches) **
  6.2      = % of bases opposite a gap in the query sequence (deleted bp)
  0.0      = % of bases opposite a gap in the repeat consensus (inserted bp)
  HSU08988 = name of query sequence
  6563     = starting position of match in query sequence
  6781     = ending position of match in query sequence
  (22462)  = no. of bases in query sequence past the ending position of match
  C        = match is with the Complement of the repeat consensus sequence
  MER7A    = name of the matching interspersed repeat
  DNA/MER2_type = the class of the repeat, in this case a DNA transposon 
            fossil of the MER2 group (see below for list and references)
  (0)      = no. of bases in (complement of) the repeat consensus sequence 
             prior to beginning of the match (0 means that the match extended 
             all the way to the end of the repeat consensus sequence)
  337      = starting position of match in repeat consensus sequence
  104      = ending position of match in repeat consensus sequence
  20       = unique identifier for individual insertions 

  An asterisk (*) following the final column (see below example)
  indicates that there is a higher-scoring match whose domain partly
  (<80%) includes the domain of the current match.

```
Please let me know if you want more details or if I wasn't clear.

Best,

Clément

**Comment by Tidler123** [comment]
Thank you,
That helped a lot

**Comment by clemgoub** [comment]
You're welcome!
