### ISSUE TITLE
RepeatMasker.lib 

### ISSUE THREAD

**Issue by dlata** [clemgoub/dnaPipeTE#31]
I am using dnaPipeTE to see what transposable elements are present in the genome of the insect species I am studying. I was having an issue with it, I will be really thankful if you can please help me through this.

I get the following error whenever I run ./test_config.sh.

"RepeatMasker.lib doesn't include the Repbase sequences! Follow instruction to install RepeatMasker libraries on https://github.com/clemgoub/dnaPipeTE"

If anyone say how can this be resolved??

**Comment by niconm89** [comment]
Hi, since the last version of RepBase is payed and you need a subscription to get it, you just can avoid this error message. Did you try to run a test?

`python3 ./dnaPipeTE.py -input test/test_dataset.fastq -output test/output_folder -genome_size 2000000 -genome_coverage 0.5 -sample_number 2`

You should be careful about the installation process because some of the dependencies downloads are not working (several links had changed), so you must manually install them in the bin folder.

Nicolás

**Comment by clemgoub** [comment]
Yes Nicolás you are right. I need to update dnaPipeTE absolutely to take this into account. 2019 was a crazy year, but 2020 should be more open... Hopefully!
