### ISSUE TITLE
TE consensus sequences

### ISSUE THREAD

**Issue by zhaolina0827** [clemgoub/dnaPipeTE#41]
Hello,

 I want to ask a question. In the output_folder , which file is the result of TE consensus sequences?
thanks in advance

Thanks,
Lina Zhao

**Comment by clemgoub** [comment]
Hello!

The contigs are in 'Trinity.fasta'

Best,

Clément

**Comment by zhaolina0827** [comment]
Dear Clément:
Sorry, I still have some questions. Regarding the issue of consensus sequences, I want to use consensus sequences to construct a phylogenetic tree of transposons, but Trinity.fasta is not the consensus sequence I want (this file contains all contigs). Is it scientifically meaningful to use Best_RM_annot_80 data to construct a phylogenetic tree of transposons? The second question is, I want to know which file is the copy number data in?The last question is, does the dnaPipe software quantify the superfamily? If so, which file is it in?
 

Thanks,
Lina Zhao

**Comment by clemgoub** [comment]
Hi Lina,

It would be a good place to start if you have enough contigs in this category. These should be the "most complete" consensi according to the reference TE file. However, because dnaPipeTE is based on sampling, the least the TE is repeated, the least complete the consensus will be in "Trinity.fasta". So by using this file only, you will only consider the most abundant families.

You can try to first cluster all the sequences in the Trinity.fasta to identify related contigs (with CD-HIT-EST for example). You can then run multiple alignments on the clusters of interests to identify conserved regions.
Another thing can be to search for ORFs in the Trinity.fasta file and cluster and align the translated proteins.

To get the copy number, you have to infer it based on the counts in "reads_per_component_and_annotations". This gives you the total bp and total reads count per contig. To normalize, the total reads count and bp can be obtain from the file "renamed_blasting_reads.fasta".

Please let me know if you have more questions,

Best,

Clément

**Comment by zhaolina0827** [comment]
Dear Clément:
Sorry, I still have some questions. I want to know which file of output _folder is file1,file2, and file3（in  landscapes.R）? Because when I was running dnaPipeTE, there was no landscape, but only annotations.
[landscape.pdf](https://github.com/clemgoub/dnaPipeTE/files/5854795/landscape.pdf)

**Comment by clemgoub** [comment]
Hello! no problem:

```Rscript landscapes.R reads_landscape factors_and_colors blast_reads.counts```

The output will be "Rplot.pdf" 

Cheers.

Clément
