### ISSUE TITLE
Question on input

### ISSUE THREAD

**Issue by jcerca** [clemgoub/dnaPipeTE#44]
Dear Clément,

happy new year. Thank you for all your help before in running dnaPipeTE. Today I spoke with a collaborator (Alex Suh), and I told him that dnaPipeTE had died since it pulled too much memory for too long in my cluster. He said that one should downscale the input data. I tried with 15Gb of input, which is 5x (3Gb genome). Alex recommended to ask you, but definitely downscale the data. I wonder if you have any recommendations on how low I should go?

Thank you for your time.
José  Cerca

**Comment by clemgoub** [comment]
Hi José, Happy new year!

Thanks for reaching out. Indeed dnaPipeTE has a Achilles' heel in the sort
of the blast outputs... As Alex suggests, I would also try to downscale the
data. For a large genome like that, I would not use more than 0.1X
(0.3Gbp). dnaPipeTE is made to work with samples < 1X. Larger values can
create files too large for the script to sort...

During my benchmarks of dnaPipeTE, I found that globally results were
consistent sampling from 0.25X with smaller genomes (droso,...) to 0.1X
with large (> 1Gb) genomes. I usually do multiple runs ranging from 0.01X
to 0.5X (with replicates) and plot the estimated repeat content according
to the coverage I used. There is not always a clear plateauing (because as
coverage increases, false positives, such as gene families start to appear
and keep increasing the repeat fraction as "NA"), but you may be able to
choose a conservative coverage in the ~0.1X range with this genome size. If
you have an annotated TE library, plot the same for each class (using
"Count.txt."); at some point, the % of annotated TE should plateau while
"NA" keep going. Usually I set the coverage there with the rationale that
if I go further I will have too much false positive.

Happy to help you or discuss this further!

Cheers,

Clément

**Comment by jcerca** [comment]
This really helped, and I hope it helps others in the future.

Thank you Clément; and all the best,
José

**Comment by clemgoub** [comment]
No problem! My pleasure!

Stay safe!
