### ISSUE TITLE
Installation issue: blastx & makeblastdb not found

### ISSUE THREAD

**Issue by Anh-Thu-Weber** [clemgoub/dnaPipeTE#47]
Hi Clement,

I'm trying to install dnaPipeTE on my directory on a shared cluster (it cannot be installed like the other tools because it has to be run in the installation folder)

the installation runs fine until the blast step; I put the path to the locally installed blast
/home/datawork-lep-s/deepadapt/dnaPipeTE/bin/ncbi-blast-2.2.28+/bin

but I get the follwing errors:
/home/datawork-lep-s/deepadapt/dnaPipeTE/bin/ncbi-blast-2.2.28+/bin/makeblastdb does not exist
/home/datawork-lep-s/deepadapt/dnaPipeTE/bin/ncbi-blast-2.2.28+/bin/blastx does not exist

indeed blastx and makeblastdb are not in this directory, nor in the ncbi-rmblastn-2.2.28/bin directory

I have a local installation of blast if that helps?
Could you help me solve this issue?

Thanks in advance, and I'm looking forward to using this tool!
Alexandra

**Comment by clemgoub** [comment]
Hi Alexandra,

This is odd! Could you send me the full log/error as well as the command line you use for dnaPipeTE? (if you use a scheduler like SLURM of qsub, you can also send me your batch script).

However it's not too complicated to get these binaries back from here: https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.2.28/ncbi-blast-2.2.28+-x64-linux.tar.gz

Let me know if the binaries are there and if they work on your system.

Cheers,

Clément

**Comment by Anh-Thu-Weber** [comment]
Hi Clement,

Thanks for your quick reply!
I installed it via the shell so there's no additional command line, and there's also no additional error except for the missing binaries
But it's true that when I look in the blast folder there are not many binaries in there, so I'll download them as you suggest and will get back to you if this doesn't solve the issue!

Cheers,
Alexandra

**Comment by clemgoub** [comment]
Let me know how It goes! 

Hopefully dnaPipeTE will have a big update in 2021.......  =)

**Comment by Anh-Thu-Weber** [comment]
Hi Clement,

Some updates; 
I downloaded both blast and rmblastn again, and the installation worked
I then got the error message that the RepBase libraries were missing, so I downloaded the Dfam.h5 as suggested in issue #46 

I tried to do the test run, but strangely Trinity failed saying that bowtie2 was missing. I dowloaded Trinity again and can't find bowtie2 in the installation folder. As I have a local installation of bowtie2 I load it in the environment and it ran.

the pipeline seems to work until the end but some output files are missing:
e.g. reads_per_component_and_annotation
and all pdf files

I also load a local installation of R but our system is a bit unpractical as it is always the last environment loaded that is kept (the previous one is unloaded, sorry if this is not clear). I guess as R is not loaded in the environment the graphs are not produced (but that's minor issue if I have all tables)

Trinity assembled 35 contigs; 2 were annotated and 33 unannotated
Does that seem correct?
Or is there an issue in the assembly/annotation?

Also, can I run Trinity without bowtie2? I wouldn't have to load it in the environment then, and could load R instead

I attached:
the script I used:
[testrun_dnaPipeTE.txt](https://github.com/clemgoub/dnaPipeTE/files/5964436/testrun_dnaPipeTE.txt)

the log file:
[dnaPipeTE_test.txt](https://github.com/clemgoub/dnaPipeTE/files/5964430/dnaPipeTE_test.txt)

the output folder with all files:
[OUT_dnaPipeTE.tar.gz](https://github.com/clemgoub/dnaPipeTE/files/5964431/OUT_dnaPipeTE.tar.gz)

Thanks for your help!
Cheers,

Alexandra

**Comment by clemgoub** [comment]
Dear Alexandra,

It seems that your run went through normally. The absence of "reads_per_component_and_annotation" was not produced because it requires the running of a R script. 

The easiest would be to re-run the same command, though not loading bowtie2 but R instead. Since the files from Trinity are already produced, dnaPipeTE should skip this step and start at the RepeatMasker step. Even if it doesn't skip Trinity, it should fail without bowtie2 and skip to the next processes, including the graphs.

Let me know if that workaround works. I am working on a "fix script" for you in case this wouldn't work, but it require more testing right now =)

Let me know,

Cheers,

Clément

**Comment by Anh-Thu-Weber** [comment]
Hi Clement,

Thank you so much, it ran fine!
I have all output files and graphs.

I have a few other questions if you don't mind;
I did a full run with one of my samples (species: brittle star (echinoderm); genome size 1.9 Gb, cov 0.1x)
Trinity generated 45367 contigs, of which 5604 were annotated
there were also some repeat classes with 0 hits (LTR, MITE, Helitron, rRNA, Satellite, Tandem repeat, other)

As the % of annotated contigs is quite low, I was wondering if there was a way to relax the annotation parameters to get more contigs annotated?
I tried the -RM_t flag (0.2 value) but then I get even less contigs annotated (718); what is the default value for -RM_t?

I also have more reads, would it help to increase the coverage, e.g. 0.5x?

It's also possible that brittle star genomes are weird and their repeats are not in the databases (but then I would still expect to retrieve rRNA?)

And just to clarify; the 'na' category are repeats without annotation?
How is it different from single/low copy DNA? Is there a coverage threshold? e.g. 10x?

Thanks again for your help!

Cheers,
Alexandra

**Comment by clemgoub** [comment]
Hi Alexandra,

I'm glad it works! There are multiple possibility for your results:

- the simplest is as you describe, that your model as only a few similar TE in the database. Especially if you used the DFAM vs Repbase.

-  For the rRNA, and all annotations in general, dnaPipeTE is sensitive to the nomenclature. Because I developed dnaPipeTE with Repbase, the annotation relies on the Repbase/RepeatMasker nomenclature (TEname#subclass/superfamily). If the repeat in the database has a different nomenclature, it might not be recognized by dnaPipeTE and will be counted as NA. The list of recognized TE is in the file `new_list_of_RM_superclass_colors_sortedOK`.

-  Which lead to your next question: NA are putatives repeats that did not receive a hit. They can be either unknown TE (not in the fasta database, or not named as  Repbase/RepeatMasker nomenclature) or if repeated enough, gene families and other non-TE repeats. Thus there is always a fine line when choosing coverage because it is expected that with increased coverage, low-repeat or unique content can be eventually assembled.

- RM_t is a good tool to restrict annotation to stronger hits. However, by default, the best hit is kept (no threshold), at RM_t = 0.2, only hits representing 20% of the query are kept. So you are already at the most sensitive level.

- One thing to try is to do multiple runs with increasing coverage. You can blast the "NA" contigs over different databases to try to filter out genes and non-TE. Also, you can collect the contigs assembled and manually annotate the most represented families. Then, put them back in a custom database (or merge with the one you use) and re-run dnaPIpeTE.

Let me know if this helps and thank you for using dnaPipeTE!

Cheers,

Clément

**Comment by Anh-Thu-Weber** [comment]
Hi Clement,

Thanks for the clarification, it's very useful!
I'll try to annotate these NA contigs manually then

thanks for developing this pipeline, and I'll keep an eye on the big update :)

Cheers,
Alexandra
