### ISSUE TITLE
Unique TE insertions

### ISSUE THREAD

**Issue by DR-genomics** [clemgoub/dnaPipeTE#64]
Hello @clemgoub ,

I have been running dnaPipeTE singularity version, no issues so far. 
I am trying to compare TE composition between samples. Specifically, I was wondering is it possible to identify number of unique TE insertions specific from each sample (samples belong to same species, but sampled at geographically different population sites) via dnaPipeTE pipeline? 

Thank you

**Comment by clemgoub** [comment]
Hello @DR-genomics !

The short answer to your question is probably no, unfortunately. Because dnaPipeTE is based on the analysis of random samples, variation at the scale of the copy (1 copy difference between two samples) is likely to be confounded with sampling fluctuation. However, [I have implemented a script `dnaPT_compare.sh`](https://github.com/clemgoub/dnaPT_utils#dnapt_comparesh) that compares "shared families" between two samples. You can output the results both in % genome or "equivalent copy" (total bp mapped / consensus length); however I would be cautious interpreting small variations with dnaPipeTE. It can be useful to replicate the analysis 2 or 3 times to confirm any small difference observed.

Best,

Clément
