### ISSUE TITLE
Update RepeatMasker libraries with RepBase

### ISSUE THREAD

**Issue by sigau** [clemgoub/dnaPipeTE#68]
Hi!
I installed your program using the singularity img and I try to update the RepeatMasker libraries with the RepBase library I have. So I follow what was said in the issue #46, putting my Repbase Dfam.h5 in /opt/dnaPipeTE/bin/RepeatMasker/Libraries, but there is no RepeatMasker in bin.
I find it in /opt/RepeatMasker/Libraries/ but hen I try to cp my Dfam.h5 in Libraries/ I got the error : 
cp: cannot create regular file '/opt/RepeatMasker/Libraries/Dfam.h5': Read-only file system

I try to chmod the folder, but I got the same error : 
chmod: changing permissions of '/opt/RepeatMasker/Libraries/Dfam.h5': Read-only file system

Is there another way of using RepBase with dnaPipeTE ?

Thanks so much for any help!
Gautier

**Comment by clemgoub** [comment]
Dear Gautier,

Indeed the best way would be to re-build the docker container from which the singularity is built, including Repbase. Unfortunately, due to licensing I cannot distribute Repbase. I will however update it with the latest Dfam ASAP.

You can modify the [`Dockerfile`](https://github.com/clemgoub/dnaPipeTE/blob/master/Dockerfile) (and associated script [`dockerinit.sh`](https://github.com/clemgoub/dnaPipeTE/blob/master/initdocker.sh)) in order to re-build the container with Docker (you can further convert it to a Singularity image).

In the meantime, the best/simple option would be to convert your Repbase into a fasta file which you can use externally as a library for RepeatMasker. You can use a custom fasta library with dnaPipeTE with the option `RM_lib <file.fasta>`

Thanks for pointing that out and let me know if you need further help!

Best,

Clément

**Comment by sigau** [comment]
Hi !
So I update the RepeatMasker libraries without modifying the dockerfile/initdocker.sh by following the method from dfam github ( https://github.com/Dfam-consortium/TETools).
I put it there if it can be useful for other users :

It should work on singularity or docker : 
- you create a folder new_lib
-  you open the container and mount the new_lib folder
- cp /opt/RepeatMasker/Libraries/* /mnt/new_lib
- you cp your new Dfam.h5 and RMRBSeqs.embl in new_lib
- addRepBase.pl -libdir /mnt/new_lib

Then you should have a new RepeatMaskerLib.h5 with your update libraires

Anyway thank you Clement for your help and for the pipeline,

Best,

Gautier

**Comment by clemgoub** [comment]
Hello and thank you Gautier for sharing your solution here!
