### ISSUE TITLE
rm: unable to remove "blast_contigs_1_fmtd": File or directory does not exist

### ISSUE THREAD

**Issue by pyrevo** [clemgoub/dnaPipeTE#7]
Dear @clemgoub,

I'm trying to setup my dnaPipeTE installation using the test dataset for the first analysis.

Trinity and RepeatMasker seems to work properly, however I still have a problem during the
estimation of repeat phase, after the third Blast run. It seems that some files were not created
so it is impossible to remove them. Since my test folder is named "prova1", I ran:

>python3 ./dnaPipeTE.py -input test_dataset.fastq -output prova1/ -genome_size 10000000 -genome_coverage 0.1 -sample_number 1

results are different from those provided in the test directory and I have this error:

>rm: unable to remove "prova1 // blast_contigs_1_fmtd": File or directory does not exist

This is a short version of the log file:

`Start time: Mon May 15 17:49:27 2017
sampling file found, skipping sampling...
Trinity files found, skipping assembly...
prova1/Annotation/Best_RM_annot_80-80
#######################################
#######################################

RepeatMasker version open-4.0.6
Search Engine: NCBI/RMBLAST [ 2.2.27+ ]
Master RepeatMasker Database: ./bin/RepeatMasker/Libraries/RepeatMaskerLib.embl ( Complete Database: 20150807 )

analyzing file prova1/Trinity.fasta

Some previous RepeatMasker output files were moved to the directory 
prova1//Trinity.fasta.preMonMay151749272017.RMoutput 
in order not to overwrite them.

Checking for E. coli insertion elements
identifying Simple Repeats in batch 1 of 1
identifying matches to root sequences in batch 1 of 1
identifying Simple Repeats in batch 1 of 1
processing output: 
cycle 1 
cycle 2 
cycle 3 
cycle 4 
cycle 5 
cycle 6 
cycle 7 
cycle 8 
cycle 9 
cycle 10 
Generating output... 
masking
done
24 line read, sorting...
sort done, filtering...
15 lines in one_RM_hit_per_Trinity_contigs
0 lines in Best_RM_annot_80
12 lines in Best_RM_annot_partial
Done
#########################################
#########################################
Done

Making blast sample...
sampling file found, skipping sampling...
total number of reads: 100125
maximum number of reads to sample:  12048 
fastq :  test_dataset.fastq
sampling 1 samples of max 12048 reads to reach coverage...
999984 bases sampled in 12048 reads 
s_test_dataset.fastq_blast done.
#######################################################
#######################################################
Blast 1 files found, skipping Blast 1 ...
###################################################
###################################################
Blast 2 files found, skipping Blast 2 ...
#####################################################
#####################################################
Blast 3 files found, skipping Blast 3 ...
#######################################################
#######################################################
parsing blastout and adding RM annotations for each read...
awk: riga com.:1: attenzione: sequenza di escape `\$' considerata come semplice `$'
rm: impossibile rimuovere "prova1/blast_contigs_1_fmtd": File o directory non esistente
Done, results in: blast_out/blastout_final_fmtd_annoted
#########################################
#########################################
Drawing graphs...
null device 
          1 
null device 
          1 
null device 
          1 
null device 
          1 
Warning message:
Removed 3 rows containing missing values (geom_bar). 
Warning message:
Removed 3 rows containing missing values (geom_bar). 
Done
Removing Trinity runs files...
find: "prova1/Trinity_run*": File o directory non esistente
done
Finishin time: Mon May 15 17:49:46 2017
########################
#   see you soon !!!   #
########################`

In my test analysis LTR/Pao are absent from file landscape.pdf output whereas Counts.txt looks just like yours. Which is the problem? Any help will be greatly appreciated. 

Thank you in advice,
Massimiliano.

**Comment by clemgoub** [comment]
Hi @pyrevo, sorry for my late reply...
I'm reading your message now and I will try to give you an answer today ASAP!
Clément

**Comment by clemgoub** [comment]
Ok, 

Here is a few checks that you can do:

1. In your command line remove the "/ " at the end of the output folder. It will prevent from creating command lines with two // in some path that may be misinterpreted by some programs. Not sure it is a source of errors but I would do it.

2. "blast_contigs_1_fmtd" is actually never created by dnaPipeTE and it seems to be an old bug. I was a previous intermediary file, and I guess I never removed the line in the code which tries to remove that file. I will fix it soon.

3. Regarding your last question, try to run manually this command from the dnaPipeTE folder:

`Rscript landscapes.R <path-to-output-folder>/reads_landscape <path-to-output-folder>/factors_and_colors`

it should create in your the dnaPipeTE folder a file called "landscape.pdf". Tell me if the Pao appears and/or any error messages you have

4. The sample test is small, so results can be different from the one I provide in example due to sampling fluctuation. You may want to try 3 different test runs.

5. For each independent test run, I recommend to create a new output folder. If a run fails, instead of re-running dnaPipeTE on the same folder, I would recommend while you are not 100% your installation is OK to erase your outfolder before giving another try. Because it can reuse wrongly created files.

Let me know how it goes and if you have any further question. Once again, sorry for my late reply.

Cheers,

Clément

**Comment by pyrevo** [comment]
Hi @clemgoub,

thank you very much for your answer!
Starting from your 3rd point i ran:

`Rscript landscapes.R prova1/reads_landscape prova1/factors_and_colors`

and it gives me some normal ggplot warnings:
```
Warning message:
package ‘ggplot2’ was built under R version 3.3.3 
Warning message:
Removed 3 rows containing missing values (geom_bar). 
Warning message:
Removed 3 rows containing missing values (geom_bar).
```
and now Pao appeared in the landscape.pdf new file.

Moreover, I have ran several other tests in new clean and empty folders. For example:

`python3 ./dnaPipeTE.py -input test_dataset.fastq -output prova2 -genome_size 10000000 -genome_coverage 0.1 -sample_number 1`

and results looks good. As you pointed out, results are similar but not identical.

Thus, since I do not have to worry about the error discussed in the 2nd point, I think the issue is solved.

Thank you very much for your kind support,
Massimiliano.

**Comment by clemgoub** [comment]
Glad to hear that!

Thanks for using dnaPipeTE!

Clém
