### ISSUE TITLE
Error with Trinity iterations

### ISSUE THREAD

**Issue by filonico** [clemgoub/dnaPipeTE#70]
Hi everyone! I keep getting the following error when running dnaPipeTE, even with the test dataset:

<code>awk: fatal: cannot open file `/full/path/to/output/dir/Trinity_run0/chrysalis/readsToComponents.out.sort' for reading (No such file or directory)</code>

The command I'm running is:

<code>python3 ./dnaPipeTE.py -input ./test/test_dataset.fastq -output /full/path/to/output/dir -genome_size 2000000 -genome_coverage 0.5 -sample_number 2 -cpu 2</code>

The <code>test.config.sh</code> is running properly.

How can I solve the issue? Thanks a lot!

**Comment by clemgoub** [comment]
Hello @filonico !

A few questions for you: 
- are you using the normal (1.3) or container (1.3c) version?
- Is the run still going through or you don't have input? This error is normally a simple bug, because there is no "run0" but the iterative process still look for it. Normally, it shouldn't affect the program run.

Cheers,

Clément

**Comment by clemgoub** [comment]
Hello! 

It seems fine indeed. The last error is related to R, and if you happen to have missing graphs, I encourage you to try these companions scripts to re-generate them (in even better!). https://github.com/clemgoub/dnaPT_utils

Let me know though if you identify issues!

Cheers,

Clément

**Comment by filonico** [comment]
Hello Clément! The script seems indeed to be working and to succeed in creating the outputs. Unfortunately I bumped into another issue regarding the dnaPT_utils scripts. As a matter of fact, when running either `dnaPT_chart.sh` or `dnaPT_landscape.sh` on my output directory I get:

```
input dataset:      /path/to/my/dir/
output folder:      /path/to/my/dir/
output prefix:      prefix
custom ylim:        FALSE
── Attaching packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.3.1 ──
✔ tibble  3.1.6     ✔ dplyr   1.0.9
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1
✔ purrr   0.3.4     
── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
Error in col.bars[i] <- cols$V2[grep(pattern = paste("^", levels(as.factor(rca_t$t_subc))[i],  : 
  replacement has length zero
Execution halted
All done, results in /path/to/my/dir/
```
I obviously checked whether there were problems with R or some other packages, but I couldn't find anything, also considering that the dnaPT_utils scripts runs **perfectly well** on the `test_dataset.fastq` provided with dnaPipeTE.
Do you have any guess of what might the problem be? I can provide the dnaPipeTE output files that are necessary for the script, if needed.

Thank you a lot for your time! Best regards

**Comment by clemgoub** [comment]
Hello @filonico !

It seems your issue is related to the one posted [here](https://github.com/clemgoub/dnaPT_utils/issues/1). Would you mind reposting or commenting there according to the respond I gave to @Liuxuanzeng ?

If this is not due to the data, then I will have to see if there is not something wrong in the code!

Thanks a lot and sorry for the issue!

Clément
